apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rabbit-direct-echo.fullname" . }}
  labels:
    {{- include "rabbit-direct-echo.labels" . | nindent 4 }}
data:
  {{- (.Files.Glob "configmap/*").AsConfig | nindent 2 }}